'use client';
import Head from "next/head";
import React, { MouseEventHandler } from "react";
import { random } from 'lodash'
import { LazyImage } from "./Components/RandomFox";
import { useState } from "react";

const myRandom = () => random(1, 123);

//generate  simple unique id
const generateId = () => Math.random().toString(36).substring(2, 9);


export default function Home () {
const [images, setImages] = useState<Array<IFoxImageItem>>([
  /* { id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg`},
  { id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg`},
  { id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg`},
  { id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg`}, */
])

const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
   const newImageItem: IFoxImageItem = {
    id: generateId(),
    url:`https://randomfox.ca/images/${myRandom()}.jpg`
  }

  setImages([
    ...images,
    newImageItem
  ]);
  window.plausible('add_fox');
}

  return (
    <div>
      <Head>
        <title>PLATZI</title>
        <meta name='description' content='Generated by Platzi'/>
        <link rel='iconic' href='/favicon.ico' />
        <script defer data-domain="yourdomain.com" src="https://plausible.io/js/script.js"></script>
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <button onClick={addNewFox}>Add new Fox</button>
        {images.map(({ id, url }) => (
          <div key={id} className='p-4'>
            <LazyImage               
              src={url} 
              width={320}
              height='auto'
              title='Random Fox'
              className='rounded bg-gray-300'
              onClick={() => console.log('hey')} />
          </div>
          
        )) }      
      </main>

      <footer>

      </footer>
    </div>
  );
}
